# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

wrapper_optimizer <- function(init_state, par_times, param_idx_cuts, lb_, ub_, state_measured, state_idx_cuts, integration_times, reltol, absolute_tolerances, fct, nswarm, ngen, error, solvertype) {
    .Call(`_paropt_wrapper_optimizer`, init_state, par_times, param_idx_cuts, lb_, ub_, state_measured, state_idx_cuts, integration_times, reltol, absolute_tolerances, fct, nswarm, ngen, error, solvertype)
}

wrapper_solver <- function(init_state, par_times, param_idx_cuts, parameter_vec, state_measured, state_idx_cuts, integration_times, reltol, absolute_tolerances, fct, solvertype) {
    .Call(`_paropt_wrapper_solver`, init_state, par_times, param_idx_cuts, parameter_vec, state_measured, state_idx_cuts, integration_times, reltol, absolute_tolerances, fct, solvertype)
}

